# Generated by Django 4.0.5 on 2022-06-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Burgers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('protein', models.CharField(max_length=255, verbose_name='Протейин')),
                ('Carbohydrates', models.CharField(max_length=255, verbose_name='Углеводы')),
                ('colories', models.CharField(max_length=255, verbose_name='свет продукта')),
                ('img', models.ImageField(upload_to='', verbose_name='фото продукта')),
            ],
        ),
        migrations.CreateModel(
            name='Stuffed_berger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title2', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
